"""
LTX Spatial Upsampler engine (diffusers in-process).

Latent-space upscaler designed specifically for LTX-Video 2 output.
Temporally aware — preserves motion consistency across frames.
~12GB VRAM with sequential offload.

Only works on clips generated by LTX-Video 2 (latent-space upscaling).
"""

from __future__ import annotations

import logging
from typing import TYPE_CHECKING

from musicvision.upscaling.base import UpscaleEngine, UpscaleInput, UpscaleResult
from musicvision.utils.video import get_video_resolution

if TYPE_CHECKING:
    from musicvision.utils.gpu import DeviceMap

log = logging.getLogger(__name__)


class LtxSpatialEngine(UpscaleEngine):
    """LTX Spatial Upsampler via diffusers LTXLatentUpsamplePipeline."""

    def __init__(
        self,
        model_id: str = "Lightricks/ltxv-spatial-upscaler-0.9.7",
        num_inference_steps: int = 10,
        device_map: DeviceMap | None = None,
    ):
        self._model_id = model_id
        self._steps = num_inference_steps
        self._device_map = device_map
        self._pipe = None
        self._loaded = False

    def load(self) -> None:
        try:
            import torch
            from diffusers import LTXLatentUpsamplePipeline
        except ImportError as e:
            raise RuntimeError(
                "LTX Spatial Upsampler requires diffusers with LTXLatentUpsamplePipeline. "
                "Install from git main: pip install git+https://github.com/huggingface/diffusers"
            ) from e

        log.info("Loading LTX Spatial Upsampler: %s", self._model_id)
        self._pipe = LTXLatentUpsamplePipeline.from_pretrained(
            self._model_id,
            torch_dtype=torch.bfloat16,
        )
        self._pipe.enable_sequential_cpu_offload()
        self._loaded = True
        log.info("LTX Spatial Upsampler loaded")

    def upscale(self, input: UpscaleInput) -> UpscaleResult:
        if not self._loaded or self._pipe is None:
            raise RuntimeError("Engine not loaded. Call load() first.")


        source_res = get_video_resolution(input.video_path)
        input.output_path.parent.mkdir(parents=True, exist_ok=True)

        # Load video frames
        from diffusers.utils import export_to_video, load_video

        video_frames = load_video(str(input.video_path))

        # Run upscale pipeline
        result = self._pipe(
            video=video_frames,
            num_inference_steps=self._steps,
            output_type="pt",
        )

        # Export frames to video
        export_to_video(result.frames[0], str(input.output_path), fps=24)

        output_res = get_video_resolution(input.output_path)
        return UpscaleResult(
            video_path=input.output_path,
            source_resolution=source_res,
            output_resolution=output_res,
            metadata={"model": self._model_id, "steps": self._steps},
        )

    def unload(self) -> None:
        if self._pipe is not None:
            del self._pipe
            self._pipe = None
            try:
                import torch
                torch.cuda.empty_cache()
            except Exception:
                pass
        self._loaded = False
        log.info("LTX Spatial Upsampler unloaded")

    @property
    def is_loaded(self) -> bool:
        return self._loaded
